project:
  type: book

book:
  title: "Mixfix operators will change the world (here's why)"
  author: "Nick Chaiyachakorn and OpenAI o3"
  date: "today"
  chapters:
    - index.qmd
    - chapters/gfdl.qmd
# Temporary navbar configuration denoting WIP
  sidebar:
    header: "<span style=\"color: red; font-size: 48px; font-weight: bold; text-decoration: underline;\">WIP</span>"

format:
  html:
    theme: cosmo
    embed-resources: true
    toc: true

jupyter: python3

execute:
  enabled: true